name: CI/CD Pipeline

on:
 push:
  branches:
   - main
   
jobs:
 build_push_deploy:
  runs-on: ubuntu-latest

  steps:
   - name : Checkout code
     uses: actions/checkout@v4

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1

   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USER }}
      password: ${{ secrets.DOCKERHUB_PASS }}

   - name: Build and push Docker image
     run: |
      docker build . -t sandhyakc/helloworld:latest
      docker push sandhyakc/helloworld:latest

       script: |
        sudo docker pull sandhyakc/helloworld:latest
        sudo docker compose -f /home/skc/helloworld/docker-compose.yml up -d
      
